### ISSUE TITLE
Use fish_indent

### ISSUE THREAD

**Issue by faho** [wwwjfy/emacs-fish#20]
I'd like to use fish_indent to automatically format my fish scripts to the proper style - like `gofmt` does for go (and go-mode offers it both standalone and as a hook).

I'd add it myself but unfortunately my elisp is weak.

**Comment by wwwjfy** [comment]
I've considered that. But the downside is we cannot define the indent. AFAIK, fish_indent doesn't have such config

**Comment by faho** [comment]
Well, go-mode adds it as a function to manually execute and documents setting it as before-save-hook.

**Comment by wwwjfy** [comment]
Right. But if I'm not a fan of tab, but space for indention, I won't like gofmt to convert all spaces to tabs.
(if I remembered correctly, it does that)

**Comment by faho** [comment]
Well, first of all I think most indentation talk is pure bikeshedding, and consistency matters above all. For that, having a tool rule over this is a good thing.

Secondly, I'm not asking for fish_indent to replace everything else, I'm just asking for go-mode-like optional integration.

**Comment by wwwjfy** [comment]
OK, I think it makes sense to be optional
