### ISSUE TITLE
Make a release so melpa-stable picks it up

### ISSUE THREAD

**Issue by faho** [wwwjfy/emacs-fish#21]
Pretty much what it says on the tin. I prefer not enabling melpa so it doesn't upgrade all my packages to git versions, so I'm currently using this via a local copy.

**Comment by cap10morgan** [comment]
+1 This would be very useful and is very easy to do:

* `git tag 0.1` (or whatever version you want to call it)
* `git push --tags`

**Comment by wwwjfy** [comment]
Sure, I wanted to wait for #20, but it doesn't matter to tag another one.

I've tagged the latest commit 0.1.0. Never used melpa-stable before, I guess no other need to be done.

**Comment by cap10morgan** [comment]
@wwwjfy Awesome, thanks! http://stable.melpa.org/#/fish-mode
