### ISSUE TITLE
"else if" not handled correctly

### ISSUE THREAD

**Issue by alphapapa** [wwwjfy/emacs-fish#22]
This code causes incorrect indentation:
```fish
function foo
    if something
        echo 
    else if bar
        echo 
    else
        echo 
    end
    end
```
As you can see, the last `end` should not be indented.  Any following lines are indented an extra step.  If the `else if` is removed, it gets indented correctly.

**Comment by alphapapa** [comment]
I was able to fix this bug with #23.  I'm a novice at elisp, so this is probably not the best way to do it, but it works.  Feel free to ignore my PR and fix it better if you like.  :)

**Comment by alphapapa** [comment]
Thanks for fixing this...but it doesn't seem to work.  I installed the new version from MELPA, but now when I try to indent a script that indented properly before (either with the "else if" and my commit, or without the "else if" and without my commit), now I get a message in the minibuffer: `Found unmatched 'end' term`.  The script in question also indents properly when run through `fish_indent`.

BTW, I wonder if it would be feasible to just use `fish_indent` to handle indentation...

**Comment by wwwjfy** [comment]
Sorry, I should've tested more before committing. I think the new commit fixes the problem.
Please give it a try.
