### ISSUE TITLE
 Symbol's value as variable is void: fish-builtins

### ISSUE THREAD

**Issue by gaydenko** [wwwjfy/emacs-fish#29]
Hi! On installing from melpa have got:
```txt
Compiling file /home/user/.emacs.d/elpa/fish-mode-20151105.134/fish-mode.el at Thu Jan 14 12:18:03 2016
fish-mode.el:121:1:Error: Symbol's value as variable is void: fish-builtins
```
Up to date Arch Linux is in use.

**Comment by wwwjfy** [comment]
Thanks for reporting this, I didn't notice the error.
It shouldn't affect normal usage without compilation to .elc, and I'll figure a way out for this.

**Comment by wwwjfy** [comment]
Hi @gaydenko, this should be fixed, please let me know if it doesn't work. Thanks!

**Comment by gaydenko** [comment]
@wwwjfy , thanks! - I'll look at it as fast as new version will ship to melpa.

**Comment by gaydenko** [comment]
@wwwjfy , 
Yes, in new release from MELPA compilation is OK, thanks!
