### ISSUE TITLE
fish-mode breaks lesser known TAP producer (fishtape) special syntax

### ISSUE THREAD

**Issue by bucaran** [wwwjfy/emacs-fish#30]
I know this is probably out of the scope of fish-mode, or very hard to do since you use `fish_indent` to indent the code dynamically, but I wrote this TAP producer in fish ([fishtape](https://github.com/fishery/fishtape)) that among some of the strange things it does, it lets you write "test" files that use a special syntax, which is later transpiled into fish code.

A test file looks like this:

```fish
test "math still works"
    1 = 1
end
```

With fish-mode, the above becomes:

```fish
test "math still works"
1 = 1
end
```

because as you know, that first snippet was **not** valid fish code. The problem is, that just happens to break fishtape that needs the indentation to be there to work :sweat_smile: 

Would you be willing to discuss how we could offer support to fishtape in fish-mode?

Cheers!

**Comment by alphapapa** [comment]
I'm just an occasional contributor to `fish-mode`, so my opinion isn't important here, but I'm guessing that the best way to do that would be to have a separate `fishtape-mode`.  Making it work might be as simple as forking `fish-mode` and making `test` a top-level keyword.  If so, maybe it could be maintained in the same repo so it could be kept in sync with other improvements to `fish-mode`.

**Comment by bucaran** [comment]
@alphapapa Yeah, I have to agree with you, I just wanted to stir up some conversation and see where that could lead to. 

The transpilation step in fishtape is so crazy, that I don't even know whether I could fix it at this point, but I should either follow your advice, or rewrite fishtape, or write a new one.

**Comment by alphapapa** [comment]
Hey, fin looks pretty interesting.  :)

**Comment by wwwjfy** [comment]
I think let the editor guess which kind of file it is might not be a good idea. I would like a specific way for the editor to know how to parse/highlight it, e.g. by file extension, by comment line in first lines, among many other ways.

PS, your repos seem interesting to me, thanks for letting me know, so I can dig. :)
