### ISSUE TITLE
Escaped quotes break syntax highlighting

### ISSUE THREAD

**Issue by faho** [wwwjfy/emacs-fish#31]
From the git completion script:

```fish
complete -f -c git -n "__fish_git_using_command submodule; and not __fish_seen_subcommand_from $submodulecommands" -a 'sync' -d 'Sync submodules\' URL with .gitmodules'
complete -f -c git -n "__fish_git_using_command submodule; and not __fish_seen_subcommand_from $submodulecommands" -s q -l quiet -d "Only print error messages"
```

The `\'` is still recognized as a single quote by the highlighter, causing it to highlight `Sync submodules\` as string, and then everything after `gitmodules'` (including the entire next line) as a string again.

**Comment by alphapapa** [comment]
Hey, thanks, turned out to be a very simple fix.  :)  @wwwjfy can merge when he's ready.

**Comment by wwwjfy** [comment]
Cool. @alphapapa Thanks a lot!
