### ISSUE TITLE
company dabbrev code doesn't complete anything in fish mode

### ISSUE THREAD

**Issue by amosbird** [wwwjfy/emacs-fish#33]
Hi, Long time user,  the title says it all really.

Tried googling for that but not much luck.

No Joy. This maybe more of a company or dabbrev question, but it does relate to fish-mode. I can't be the only person to wish this, can I?

Anyway, thanks for listening.

If it's impossible, I'll just not bother with dabbrev code. 

Cheers, Amos

**Comment by wwwjfy** [comment]
Sorry for the delay.
I don't use `company`, but I gave a try just now and it seems to work in my setup.
I just installed it, without any configuration.

Is this like something you want? (The bottom half is the output of `company-diag`)
![screen shot 2017-11-12 at 10 21 59](https://user-images.githubusercontent.com/126527/32695327-75266e98-c793-11e7-95c3-e4ad7d3c7ab8.png)

**Comment by amosbird** [comment]
Oh, it seems I have some uncleaned `elc` files clobbering this. Clearing them makes it work. Thanks!
