### ISSUE TITLE
Wrong (no, or now too much) indentation on continuation lines

### ISSUE THREAD

**Issue by tsdh** [wwwjfy/emacs-fish#37]
I frequently break longer commands on multiple lines.  Currently, fish-mode doesn't indent the continuation lines, e.g., you have:

```fish
find . \
-type f \
-name '*.c'
```
fish itself in the line editor and `fish_indent` would indent it like this:

```fish
find . \
    -type f \
    -name '*.c'
```
This is much more readable and matches also the indentation of sh-mode for bash/zsh.

**Comment by Holt59** [comment]
Facing the same issue. Indentation is incorrect but also it breaks coloring for subsequent lines.

**Comment by tsdh** [comment]
In the latest release (Package-Version: 20200210.1815), the indentation of continuation lines has changed, and now it indents too far.

```fish
function print_status
    foo \
        bar \
            baz \
                quux
end

find . \
    -type f \
        -name '*.c'
```

**Comment by wwwjfy** [comment]
@alphapapa could you take a look?

**Comment by alphapapa** [comment]
Thanks, I'll try to fix it.

**Comment by alphapapa** [comment]
Ok, this seems to fix it.  I added to the syntax test file as @tsdh demonstrated: https://github.com/wwwjfy/emacs-fish/commit/3b5c1a122d876221b1f7a91a13b2914f8c25e432#diff-eb0d9d5033cf2d3b3a101769101181eb  Please let me know if this fixes it for you.

**Comment by alphapapa** [comment]
Well, this is not quite right either. because this doesn't work properly:

```fish
set -l var \
    (math "1 + 1")
    set -l another_var \
        (math "2 + 2")
```

I'm adding that to the test file and working on it...

**Comment by alphapapa** [comment]
Ok, that should do it.  The test file shows correct indentation in all of its cases.  I'll see if I can simplify the code further while preserving correct behavior.

**Comment by alphapapa** [comment]
Simplified here: https://github.com/wwwjfy/emacs-fish/commit/db257db81058b0b12f788c324c264cc59b9a5bf4

**Comment by tsdh** [comment]
@alphapapa I can confirm that the current MELPA version `Package-Version: 20200213.2137` fixed the issue.  Thanks a lot!
