### ISSUE TITLE
Improper Indentation

### ISSUE THREAD

**Issue by Ironlenny** [wwwjfy/emacs-fish#43]
I have this:
```
set students (awk -F "\t" -v crn=$crn '{ if($2 ~ crn) {print $1}}' $class_info)
        set port 5000
```
It should look like this:
```
set students (awk -F "\t" -v crn=$crn '{ if($2 ~ crn) {print $1}}' $class_info)
set port 5000
```
This is what seems to be throwing fish-mode off:
```
'{ if($2 ~ crn) {print $1}}'
```

**Comment by wwwjfy** [comment]
It works properly for me.
The statements wrapped in `"` or `'` are considered as strings (can tell due to different highlights).

**Comment by Ironlenny** [comment]
I need to update the package.
