### ISSUE TITLE
Improper pairing of quotes

### ISSUE THREAD

**Issue by Ironlenny** [wwwjfy/emacs-fish#44]
If I have a quote in a command such as this:
```
echo $user_name:(echo $name[1]$name[2]$student | tr -d '["]') | chpasswd
```
It will pair `'["` with the next quote it finds. This is not expected behaviour. It should be ignoring the single quote since I'm passing the quote as an argument to `tr`. I suspect there's similar issues with other paired delimiters.

**Comment by wwwjfy** [comment]
It works properly for me.
Also put together with the other issue #43, I feel it's an environmental issue.

**Comment by Ironlenny** [comment]
Yeah, turns out I need to update the package. Thanks for the response.
