### ISSUE TITLE
indentation causes infinite loop when first line in buffer is continued

### ISSUE THREAD

**Issue by paulmr** [wwwjfy/emacs-fish#46]
If you start a new empty buffer in `fish-mode` and enter a continued line, such as:

```fish
echo hello \
```

then when you press enter at the end of the line, emacs will freeze until you quit with `C-g`.

Looking at the implementation of `(fish-get-normal-indent)` it looks like it is getting stuck in an infinite loop in `(back-to-non-continued)`:

```elisp
    (cl-labels ((back-to-non-continued
                 () (cl-loop do (forward-line -1)
                             while (line-continued-p)))
                (line-continued-p
                 () (save-excursion
                      (forward-line -1)
                      (looking-at-p (rx (1+ nonl) "\\" eol)))))
```

A simple fix for this is changing the while condition to:

```
(and (not (bobp)) (line-continued-p))
```

**Comment by m4xxed** [comment]
Hello, just checking in. I have had the same error and funnily enough found the same solution. I have updated it in my local repo, but why is this fix not getting accepted?

**Comment by wwwjfy** [comment]
Sorry but I'm not actively using it and monitoring this repo any more.
Applied the suggested fix. Thanks both
