### ISSUE TITLE
Feature request: support fish 3.4's `"$(...)"` syntax

### ISSUE THREAD

**Issue by andmis** [wwwjfy/emacs-fish#48]
(See the release notes: https://fishshell.com/docs/current/relnotes.html.)

**Comment by andmis** [comment]
Just glancing at the code, does this work for examples like `echo "Some numbers are $(seq 5)"`, where the `$(...)` is in double quotes?

**Comment by wwwjfy** [comment]
I see. I misunderstood it. thought it's only to add support of $
will reopen it.

**Comment by andmis** [comment]
If I'm reading the code right, this will fail on things like `echo "$(echo ')')"`. Which may be acceptable.

**Comment by wwwjfy** [comment]
Right.
I checked the implementation of shell script. It's quite complex to parse the syntax inside a string.
It'll take some time to get there.
